### PR TITLE
fix resolving dependencies via nested names

### PR DESCRIPTION
**Pull request by ermolaev**

### CODE REVIEW

**Comment by timriley** [comment]
My only thought here would that it'd be worth following a similar approach to dry-auto_inject's name detection code, so we have consistent handling across the two. For that, see https://github.com/dry-rb/dry-auto_inject/blob/045cbd46be4338ad37ac4278b5cd72ad37d76dc8/lib/dry/auto_inject/dependency_map.rb#L42-L47. This uses a regex, so it's agnostic to the separator character being used.

**Comment by ermolaev** [comment]
Thanks for the clarification, I updated code

**Comment by solnic** [comment]
FYI Codacy got stuck analysing this PR so let's just ignore it here 🤷🏻

**Review by solnic — APPROVED** [review]

**Comment by flash-gordon** [comment]
Thank you for this, I'll be merging and doing a few tweaks. For instance, we usually have errors in a separate module and have their names ending with `Error` (ruby convention more or less)

**Pull request merged**
